In [40]:
def readFASTAs(fileName):

    with open(fileName, 'r') as file:
        v = []
        genome = ''
        for line in file:
            if line[0] != '>':
                genome += line.strip()
            else:
                v.append(genome.upper())
                genome = ''
        v.append(genome.upper())
        del v[0]
        return v

In [41]:
Sequences = readFASTAs('hotCold.txt')

In [42]:
len(Sequences)

1081

In [43]:
import itertools
import numpy as np

In [44]:
def generate(X):

    elements = 'ACGT'

    T = []
    for x in X:
        t = []
        for i in range(1, 4 + 1, 1):
            v = list(itertools.product(elements, repeat=i))
            for i in v:
                t.append(x.count(''.join(i)))
        T.append(t)

    T = np.array(T)

    return T

<br/>

* K-mer 

In [45]:
K_mer = generate(Sequences)
np.save(file = "K-mer", arr = K_mer)

<br/>

* Reverse complement composition of k-mers

In [46]:
rev_k = []
for sequence in Sequences:
    rev_k.append(reverseComplement(sequence))

rev_k = generate(rev_k)
np.save(file = "rev-k-mer", arr = rev_k)

In [47]:
K_mer    = np.load('K-mer.npy')
rev_k    = np.load('rev-k-mer.npy')
print(K_mer)
print("")
print(rev_k)

[[35 39 31 ...  2  0  0]
 [38 23 44 ...  0  0  0]
 [36 32 35 ...  0  1  0]
 ...
 [37 28 32 ...  1  1  1]
 [37 28 32 ...  1  1  1]
 [29 34 27 ...  1  2  1]]

[[26 31 39 ...  0  1  1]
 [26 44 23 ...  0  1  0]
 [28 35 32 ...  0  1  0]
 ...
 [34 32 28 ...  1  1  2]
 [34 32 28 ...  1  1  2]
 [41 27 34 ...  0  1  0]]
