In [1]:
def readFASTAs(fileName):

    with open(fileName, 'r') as file:
        v = []
        genome = ''
        for line in file:
            if line[0] != '>':
                genome += line.strip()
            else:
                v.append(genome.upper())
                genome = ''
        v.append(genome.upper())
        del v[0]
        return v

In [4]:
Sequences = readFASTAs('hotcoldspot.txt')

In [6]:
len(Sequences)

1081

In [14]:
import itertools
import numpy as np

In [21]:
def generate(X):

    elements = 'ACGT'

    T = []
    for x in X:
        t = []
        for i in range(1, 4 + 1, 1):
            v = list(itertools.product(elements, repeat=i))
            for i in v:
                t.append(x.count(''.join(i)))
        T.append(t)

    T = np.array(T)

    return T


In [22]:
K_mer = generate(Sequences)

In [52]:
np.shape(K_mer)



(1081, 340)

In [33]:
print(K_mer)

[[35 39 31 ...  2  0  0]
 [38 23 44 ...  0  0  0]
 [36 32 35 ...  0  1  0]
 ...
 [37 28 32 ...  1  1  1]
 [37 28 32 ...  1  1  1]
 [29 34 27 ...  1  2  1]]


In [59]:
for i in range(0, len(K_mer)):
    sum=0
    sum=(1/130)*K_mer[i]
print(sum)
    

[0.22307692 0.26153846 0.20769231 0.31538462 0.03846154 0.07692308
 0.03846154 0.06153846 0.08461538 0.03076923 0.03846154 0.1
 0.03846154 0.06153846 0.04615385 0.05384615 0.05384615 0.08461538
 0.07692308 0.06923077 0.00769231 0.02307692 0.01538462 0.
 0.03076923 0.         0.02307692 0.01538462 0.00769231 0.00769231
 0.01538462 0.00769231 0.00769231 0.01538462 0.01538462 0.02307692
 0.02307692 0.00769231 0.01538462 0.03846154 0.00769231 0.
 0.         0.02307692 0.00769231 0.00769231 0.01538462 0.00769231
 0.02307692 0.02307692 0.03076923 0.02307692 0.00769231 0.03076923
 0.         0.         0.01538462 0.00769231 0.01538462 0.02307692
 0.02307692 0.01538462 0.00769231 0.00769231 0.01538462 0.01538462
 0.00769231 0.01538462 0.00769231 0.01538462 0.00769231 0.02307692
 0.03076923 0.01538462 0.         0.03846154 0.         0.03076923
 0.01538462 0.02307692 0.00769231 0.03076923 0.02307692 0.02307692
 0.         0.00769231 0.         0.         0.00769231 0.
 0.01538462 0.         0.0

In [63]:
for i in range(0, len(K_mer)):
    if  K_mer[i]> 0:
        tdf=0
        tdf= np.log(1081/K_mer[i])
print(tdf)

    


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()